site_name: "GeoLabs Workshop-Questions"
site_description: "GeoLabs Workshop-Questions Docs"
site_author: "Geovanny Mendoza"
site_url: "https://github.com/geovannymcode/geolabs-test.github.io/"

# Repository
repo_name: "/geovannymcode/geolabs-test.github.io"
repo_url: "https://geovannymcode.github.io/geolabs-test.github.io"

# Copyright
copyright: "Copyright &copy; 2025 Geovanny Mendoza"

theme:
  name: material
nav:
  - Preguntas Java: index.md
  - Programación Funcional: fp.md
  

# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/geovannymcode"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/geovannycode"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/geovannycode/"

# Extensions
markdown_extensions:
  - codehilite
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg


# Tables
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js